# Generated by Django 4.2.7 on 2023-11-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='My Portfolio', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_52_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_52_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.stock')),
            ],
            options={
                'unique_together': {('stock', 'portfolio')},
            },
        ),
        # migrations.AlterField(
        #     model_name='stock',
        #     name='portfolios',
        #     field=models.ManyToManyField(through='main_app.StockPortfolio', to='main_app.portfolio'),
        # ),
    ]
