# Generated by Django 4.2.7 on 2023-11-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_portfolio_portfolio_name_stock_close_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='portfolios',
        ),
    ]
